contents:
  - name: 点类
    code: 点类.cpp
  - name: 直线类
    code: 直线类.cpp
  - name: 线段类
    code: 线段类.cpp
  - name: 极角排序
    code: 极角排序.cpp
  - name: 多边形
    code: 多边形.cpp
  - name: 凸包
    code: 凸包.cpp
  - name: 最小矩形覆盖
    code: 最小矩形覆盖.cpp
  - name: 半平面交
    code: 半平面交.cpp